# -*- coding: utf-8 -*-
"""중국뉴스 수집기_251222

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AeZjmDzXH27BEO73L4y3PMRhu8h1viA_
"""

# ============================================
# 일일 중국 뉴스 수집 시스템 (프로덕션)
#
# 기능:
# - 한국 시간대 기준 당일 작성 뉴스만 수집
# - 명확한 작성일이 없으면 제외
# - 년월일(YYYYMMDD) 타임스탬프로 파일 생성
# - 동일 날짜 재실행 시 덮어쓰기
#
# Google Colab용
# ============================================

!pip install anthropic
from anthropic import Anthropic
from google.colab import userdata
import json
import re
import requests
from bs4 import BeautifulSoup
import time
from datetime import datetime
import pytz
from urllib.parse import urljoin
import os

# ============================================
# 설정
# ============================================

OUTPUT_DIR = "/content/collect-output"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# 한국 시간대 (UTC+9)
korea_tz = pytz.timezone('Asia/Seoul')

# API 설정
try:
    API_KEY = userdata.get('CLAUDE_API_KEY')
    if not API_KEY:
        raise ValueError("API 키가 설정되지 않았습니다")
    print("✅ API 키 로드 완료\n")
except Exception as e:
    print(f"❌ 오류: {e}")
    raise

client = Anthropic(api_key=API_KEY)

# 뉴스 소스
NEWS_SOURCES = {
    "人民日报": {
        "url": "http://www.people.com.cn/",
        "category": "정치/정책",
        "reliability": "A"
    },
    "新华网": {
        "url": "http://www.xinhuanet.com/",
        "category": "종합뉴스",
        "reliability": "A"
    },
    "央视新闻": {
        "url": "http://news.cctv.com/",
        "category": "종합뉴스",
        "reliability": "A"
    },
    "经济观察网": {
        "url": "http://www.eeo.com.cn/",
        "category": "경제",
        "reliability": "B"
    },
    "财经网": {
        "url": "http://www.caijing.com.cn/",
        "category": "금융/경제",
        "reliability": "B"
    },
    "澎湃新闻": {
        "url": "http://www.thepaper.cn/",
        "category": "조사보도",
        "reliability": "B"
    },
    "36氪": {
        "url": "http://www.36kr.com/",
        "category": "기술",
        "reliability": "C"
    }
}

COUNTRY = "中国"

AI_PROMPT = """
중국 뉴스 분석 기자입니다.
각 제목이 실제 뉴스인지 판단하세요.

뉴스 아님: "扫码", "403", "Forbidden", 외국어만, 에러메시지
뉴스: 그 외 모두

JSON으로만 응답. 다른 텍스트 없음.
{"result": [{"idx": 1, "is_news": true, "importance": 7, "category": "경제"}]}
"""

# ============================================
# 유틸리티 함수
# ============================================

def get_today_date():
    """한국 시간대 기준 오늘 날짜 (YYYY-MM-DD)"""
    now = datetime.now(korea_tz)
    return now.strftime("%Y-%m-%d")

def get_db_filename():
    """DB 파일명 생성 (년월일 타임스탐프)"""
    now = datetime.now(korea_tz)
    date_str = now.strftime("%Y%m%d")
    return os.path.join(OUTPUT_DIR, f"chinanews_collection_{date_str}.json")

def check_duplicate(new_record, existing_records):
    """중복 확인 (언론사 + 제목 + 기사날짜)"""
    for existing in existing_records:
        if (new_record['news_source'] == existing['news_source'] and
            new_record['title'] == existing['title'] and
            new_record['article_date'] == existing['article_date']):
            return True
    return False

# ============================================
# DB 관리
# ============================================

def load_or_create_db():
    """DB 로드 또는 신규 생성"""
    db_file = get_db_filename()

    if os.path.exists(db_file):
        try:
            with open(db_file, 'r', encoding='utf-8') as f:
                db = json.load(f)
                print(f"✅ 기존 DB 로드: {len(db.get('records', []))}개 기사\n")
                return db
        except Exception as e:
            print(f"⚠️ DB 로드 실패, 새로 생성\n")

    db = {
        "metadata": {
            "country": COUNTRY,
            "sources": list(NEWS_SOURCES.keys()),
            "total_records": 0,
            "last_updated": None,
            "categories": ["정치", "경제", "기술", "기타"]
        },
        "records": []
    }
    print(f"✅ 새 DB 생성\n")
    return db

def save_db(db):
    """DB 저장"""
    try:
        db_file = get_db_filename()

        with open(db_file, 'w', encoding='utf-8') as f:
            json.dump(db, f, ensure_ascii=False, indent=2)

        file_size = os.path.getsize(db_file) / 1024
        filename = os.path.basename(db_file)

        print(f"💾 저장 완료")
        print(f"   📄 파일: {filename}")
        print(f"   📊 크기: {file_size:.1f} KB")
        print(f"   📌 총 기사: {len(db['records'])}개\n")
        return True
    except Exception as e:
        print(f"❌ 저장 실패: {str(e)}\n")
        return False

# ============================================
# 뉴스 수집
# ============================================

def collect_news(source_name, source_info):
    """뉴스 제목과 링크 수집"""
    try:
        url = source_info["url"]
        print(f"  🔗 {source_name} [{source_info['reliability']}]...", end=" ")

        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
        }

        response = requests.get(url, headers=headers, timeout=10)
        response.encoding = 'utf-8'
        soup = BeautifulSoup(response.content, 'html.parser')

        spam_keywords = [
            '·', '栏目', '分类', '导航', '菜单', '更多', '首页',
            '订阅', '登录', '注册', '频道', '搜索', '用户', '广告',
            'Русский', 'Português', 'English', 'Français', '日本語',
            '403', '404', 'Forbidden', 'Error', '错误',
            '扫码', '微信', '长按', '关注',
            '备案', '版权', 'ICP', '联系', '关于',
            '精彩内容', '最新视频', 'THE LATEST',
        ]

        raw_news = []

        # h1, h2, h3에서 수집
        for tag_name in ['h1', 'h2', 'h3']:
            for tag in soup.find_all(tag_name):
                title = tag.get_text(strip=True)
                if any(keyword in title for keyword in spam_keywords) or not (8 < len(title) < 150):
                    continue

                link = ""
                a_tag = tag.find('a')
                if a_tag and a_tag.get('href'):
                    link = a_tag.get('href')
                    if not link.startswith('http'):
                        link = urljoin(url, link)

                raw_news.append({
                    "source": source_name,
                    "source_reliability": source_info["reliability"],
                    "source_category": source_info["category"],
                    "title_zh": title,
                    "link": link
                })

        # a 태그에서도 수집
        for a_tag in soup.find_all('a'):
            title = a_tag.get_text(strip=True)
            link = a_tag.get('href', '')

            if any(keyword in title for keyword in spam_keywords) or not (8 < len(title) < 150):
                continue
            if not link or link.startswith('javascript') or any(item['title_zh'] == title for item in raw_news):
                continue

            if not link.startswith('http'):
                link = urljoin(url, link)

            raw_news.append({
                "source": source_name,
                "source_reliability": source_info["reliability"],
                "source_category": source_info["category"],
                "title_zh": title,
                "link": link
            })

        # 중복 제거
        unique_news = []
        seen = set()
        for item in raw_news:
            if item['title_zh'] not in seen:
                seen.add(item['title_zh'])
                unique_news.append(item)

        # 모든 뉴스 수집 (제한 없음)
        print(f"✅ {len(unique_news)}개")
        return unique_news

    except Exception as e:
        print(f"❌")
        return []

# ============================================
# 기사 날짜 추출
# ============================================

def extract_article_date(link):
    """원문에서 발행 날짜 추출 (명확한 경우만)"""
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        response = requests.get(link, headers=headers, timeout=8)
        response.encoding = 'utf-8'
        soup = BeautifulSoup(response.content, 'html.parser')

        patterns = [
            r'(\d{4})[年-](\d{1,2})[月-](\d{1,2})[日号]',  # 2024年12月21日
            r'(\d{4})-(\d{2})-(\d{2})',                     # 2024-12-21
        ]

        found_dates = []

        # 메타 태그 확인
        for meta in soup.find_all('meta'):
            properties = [meta.get('property', '').lower(), meta.get('name', '').lower()]
            if any(p in ['publish_date', 'article:published_time', 'og:published_time']
                   for p in properties):
                content = meta.get('content', '')
                if content:
                    match = re.search(r'(\d{4})-(\d{2})-(\d{2})', content)
                    if match:
                        found_dates.append(('메타', match.group(0)))

        # 본문 처음 2000자에서 날짜 찾기
        full_text = soup.get_text()
        for pattern in patterns:
            match = re.search(pattern, full_text[:2000])
            if match:
                if len(match.groups()) == 3:
                    year, month, day = match.groups()
                    year, month, day = int(year), int(month), int(day)

                    if 2020 <= year <= 2026 and 1 <= month <= 12 and 1 <= day <= 31:
                        date_str = f"{year:04d}-{month:02d}-{day:02d}"
                        found_dates.append(('본문', date_str))

        # 소스 정보에서 날짜 찾기
        source_section = soup.find(class_=re.compile('(source|from|byline|info)', re.I))
        if source_section:
            source_text = source_section.get_text()
            for pattern in patterns:
                match = re.search(pattern, source_text)
                if match:
                    if len(match.groups()) == 3:
                        year, month, day = match.groups()
                        year, month, day = int(year), int(month), int(day)

                        if 2020 <= year <= 2026 and 1 <= month <= 12 and 1 <= day <= 31:
                            date_str = f"{year:04d}-{month:02d}-{day:02d}"
                            found_dates.append(('소스', date_str))

        # 결과 검증 (모든 날짜가 일치해야 함)
        if not found_dates:
            return None

        unique_dates = set(date for _, date in found_dates)

        if len(unique_dates) == 1:
            return unique_dates.pop()
        else:
            # 날짜 불일치
            return None

    except Exception as e:
        return None

# ============================================
# 원문 추출
# ============================================

def get_article_content(link):
    """기사 본문 추출"""
    try:
        headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
        response = requests.get(link, headers=headers, timeout=8)
        response.encoding = 'utf-8'
        soup = BeautifulSoup(response.content, 'html.parser')

        for tag in soup.find_all(['script', 'style', 'nav', 'footer', 'noscript', 'meta']):
            tag.decompose()

        content = ""

        article = soup.find('article')
        if article:
            text = article.get_text(strip=True)
            if len(text) > 50:
                content = text

        if not content or len(content) < 50:
            for selector in ['content', 'article', 'news', 'main']:
                div = soup.find(id=selector)
                if div:
                    text = div.get_text(strip=True)
                    if len(text) > 50:
                        content = text
                        break

        if not content or len(content) < 50:
            paragraphs = soup.find_all('p')
            if paragraphs:
                valid = [p.get_text(strip=True) for p in paragraphs
                        if len(p.get_text(strip=True)) > 20
                        and '责任编辑' not in p.get_text()]
                if valid:
                    content = '\n'.join(valid[:15])

        if content:
            content = re.sub(r'\n\s*\n', '\n', content)
            if '责任编辑' in content:
                content = content.split('责任编辑')[0]
            return content[:500].strip()

        return "원문 로드 실패"
    except Exception as e:
        return "원문 로드 실패"

# ============================================
# AI 검증
# ============================================

def validate_news(raw_news_list, today_date):
    """AI 검증 + 당일 날짜 필터링 (배치 처리)"""
    if not raw_news_list:
        return []

    print(f"\n📋 검증할 뉴스 ({len(raw_news_list)}개):")
    print(f"⚠️  배치로 나누어 검증 중... (배치당 50개)\n")

    db_records = []
    batch_size = 50

    # 배치로 나누어 처리
    for batch_idx in range(0, len(raw_news_list), batch_size):
        batch = raw_news_list[batch_idx:batch_idx + batch_size]
        batch_num = batch_idx // batch_size + 1
        total_batches = (len(raw_news_list) + batch_size - 1) // batch_size

        print(f"🔍 배치 {batch_num}/{total_batches} 검증 중... ({len(batch)}개)")

        news_text = "\n".join([
            f"{i}. [{item['source']}] {item['title_zh']}"
            for i, item in enumerate(batch, 1)
        ])

        try:
            response = client.messages.create(
                model="claude-opus-4-1-20250805",
                max_tokens=3000,
                system=AI_PROMPT,
                messages=[
                    {
                        "role": "user",
                        "content": f"뉴스 검증:\n{news_text}"
                    }
                ]
            )

            response_text = response.content[0].text.strip()

            # JSON 파싱
            result = None
            try:
                result = json.loads(response_text)
            except json.JSONDecodeError:
                match = re.search(r'```json\s*(.*?)\s*```', response_text, re.DOTALL)
                if match:
                    try:
                        result = json.loads(match.group(1).strip())
                    except:
                        pass

                if result is None:
                    match = re.search(r'\{.*"result".*\}', response_text, re.DOTALL)
                    if match:
                        try:
                            result = json.loads(match.group(0))
                        except:
                            pass

            if result is None:
                print(f"⚠️  배치 {batch_num}: JSON 파싱 실패, 건너뜀\n")
                continue

            # 배치 처리 결과
            batch_added = 0
            for item in result.get("result", []):
                if item.get("is_news", False):
                    idx = item.get("idx", 1) - 1
                    if 0 <= idx < len(batch):
                        original = batch[idx]

                        # 날짜 추출
                        extracted_date = extract_article_date(original["link"]) if original["link"] else None

                        # 필터링 1: 명확한 날짜
                        if extracted_date is None:
                            continue

                        # 필터링 2: 당일 뉴스
                        if extracted_date != today_date:
                            continue

                        # 원문 추출
                        content = get_article_content(original["link"]) if original["link"] else "원문 로드 실패"
                        content_length = len(content)
                        content_status = "정상" if content_length >= 100 else ("불완전" if content_length >= 50 else "오류")

                        db_record = {
                            "collection_date": today_date,
                            "article_date": extracted_date,
                            "country": COUNTRY,
                            "news_source": original["source"],
                            "source_reliability": original["source_reliability"],
                            "source_category": original["source_category"],
                            "title": original["title_zh"],
                            "content": content,
                            "content_length": content_length,
                            "content_status": content_status,
                            "link": original["link"],
                            "category": item.get("category", "其他"),
                            "importance": item.get("importance", 5),
                            "is_validated": True
                        }

                        db_records.append(db_record)
                        batch_added += 1

            print(f"✅ 배치 {batch_num}: {batch_added}개 추가됨\n")
            time.sleep(1)  # API 레이트 제한

        except Exception as e:
            print(f"⚠️  배치 {batch_num} 오류: {str(e)}\n")
            continue

    print(f"✅ 검증 완료: {len(db_records)}개 (당일 명확한 작성일만)\n")
    return db_records

# ============================================
# 메인
# ============================================

def main():
    now = datetime.now(korea_tz)
    today_date = now.strftime("%Y-%m-%d")

    print("=" * 80)
    print("📰 일일 중국 뉴스 수집 시스템")
    print("=" * 80)
    print(f"📅 기준 날짜: {today_date} (한국 시간)")
    print(f"⏰ 수집 시간: {now.strftime('%H:%M:%S')}")
    print(f"💾 저장 파일: chinanews_collection_{today_date.replace('-', '')}.json")
    print(f"🎯 조건: 명확한 작성일 + 오늘 작성된 뉴스만\n")

    # Step 0: DB 로드
    print("=" * 80)
    print("✓ Step 0: DB 로드")
    print("=" * 80)
    db = load_or_create_db()

    # Step 1: 뉴스 수집
    print("=" * 80)
    print("✓ Step 1: 뉴스 수집")
    print("=" * 80 + "\n")

    all_news = []
    for source_name, source_info in NEWS_SOURCES.items():
        news = collect_news(source_name, source_info)
        all_news.extend(news)
        time.sleep(1)

    print(f"\n✅ 총 {len(all_news)}개 뉴스 수집")

    if not all_news:
        print("❌ 수집된 뉴스 없음")
        return

    # Step 2: 검증
    print("\n" + "=" * 80)
    print("✓ Step 2: 검증 (AI) + 날짜 필터링")
    print("=" * 80)

    db_records = validate_news(all_news, today_date)

    if not db_records:
        print("❌ 유효한 뉴스 없음 (명확한 당일 작성 뉴스 부재)")
        return

    # Step 3: 중복 필터링
    print("=" * 80)
    print("🔄 중복 필터링")
    print("=" * 80)
    existing_records = db.get("records", [])
    print(f"기존: {len(existing_records)}개")
    print(f"검증됨: {len(db_records)}개\n")

    added_count = 0
    for record in db_records:
        if not check_duplicate(record, existing_records):
            db["records"].append(record)
            added_count += 1
            print(f"✅ 추가: [{record['news_source']}] {record['title'][:50]}")
        else:
            print(f"⏭️  중복: [{record['news_source']}] {record['title'][:50]}")

    db["metadata"]["total_records"] = len(db["records"])
    db["metadata"]["last_updated"] = today_date

    print(f"\n📊 추가 결과: {added_count}개 신규\n")

    if added_count == 0:
        print("⚠️ 모든 뉴스가 중복. DB 업데이트하지 않습니다.")
        return

    # Step 4: 저장
    print("=" * 80)
    print("✓ Step 3: DB 저장")
    print("=" * 80 + "\n")

    if save_db(db):
        print(f"📈 수집 통계:")
        print(f"   수집: {len(all_news)}개")
        print(f"   검증: {len(db_records)}개 (당일 명확일)\n   신규: {added_count}개")
        print(f"   중복: {len(db_records) - added_count}개")
        print(f"\n📊 DB 현황:")
        print(f"   총 기사: {len(db['records'])}개")
        print(f"   마지막 업데이트: {db['metadata']['last_updated']}")

if __name__ == "__main__":
    main()